apiVersion: v1
kind: Pod
metadata:
  name: move-detection-model
  namespace: move-detection
  labels:
    app: move
spec:
  nodeSelector:
    worker: faasoong-worker
  containers:
  - name: move-detection
#    image: dohyunkim12/motion_detect:8.0-with-clearqueue
    image: dohyunkim12/motion_detect:8.0-demo
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8011

---
apiVersion: v1
kind: Service
metadata:
  name: move
  namespace: move-detection
  labels:
    app: move
spec:
  type: NodePort     # 서비스 타입
  ports:
  - port: 8080       # 서비스 포트
    targetPort: 8011   # 타켓, 즉 container의 포트
    protocol: TCP
    name: http
  selector:
    app: move
