apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: location
  labels:
    app: location
spec:
  replicas: 0
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-cpu-limit: "1"
        config.linkerd.io/proxy-cpu-request: "0.1"
        config.linkerd.io/proxy-memory-limit: 1Gi
        config.linkerd.io/proxy-memory-request: 128Mi
      labels:
        app: location
    spec:
      nodeSelector:
        worker: faasoong-worker
      containers:
      - name: tweet_upload
        image: dohyunkim12/tweet_upload:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 128M
            cpu: 125m
          limits:
            memory: 1024M
            cpu: 1000m

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: location-service-scaling
  namespace: location
spec:
  scaleTargetRef:
    apiVersion: apps/v1   # Optional. Default: apps/v1
    kind: Deployment         # Optional. Default: Deployment
    name: location-service         # Mandatory. Must be in the same namespace as the ScaledObject
    envSourceContainerName: tweet_upload  # Optional. Default: .spec.template.spec.containers[0]
  pollingInterval: 10                                # Optional. Default: 30 seconds
  cooldownPeriod: 10                                 # Optional. Default: 300 seconds 아예 다시 zero상태로 돌아가는데 까지 걸리는 시간
  minReplicaCount: 0                                 # Optional. Default: 0
  maxReplicaCount: 10                               # Optional. Default: 100
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: false        # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 10             # 스케일 다운하는데 걸리는 시간.
          policies:
          - type: Percent
            value: 100
            periodSeconds: 10
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://faasoong:tnd@116.89.189.12:5672/
      protocol: amqp 
      mode: QueueLength 
      value: "3" 
      queueName: fire
      vhostName: /

